baseURL = "https://blog.flockfysh.tech/"
languageCode = "en-us"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "flockfysh Blog"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = ""
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addDot = true
  addFrame = true
  highlightColor = '#7b16ff'
  baseColor = "#fffff1"
  baseOffsetColor = "#eaeaea"
  headingColor = "#1c1b1d"
  textColor = "#4e5157"
  dotColor = "#7b16ff"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'flockfysh'
    url = 'https://flockfysh.tech/'
    weight = 1
  [[menu.main]]
    name = "Tags"
    identifier = "tags"
    weight = 300
    url = "/tags/"
